name: _____serviceName_____
description: _____description_____

setup: npm install --loglevel error --depth 0
startup:
  command: node node_modules/exoservice/bin/exo-js
  online-text: all systems go
tests: node_modules/cucumber/bin/cucumber.js

messages:
  receives:
    - _____serviceName_____.create
    - _____serviceName_____.create_many
    - _____serviceName_____.delete
    - _____serviceName_____.list
    - _____serviceName_____.read
    - _____serviceName_____.update
  sends:
    - _____serviceName_____.created
    - _____serviceName_____.created_many
    - _____serviceName_____.deleted
    - _____serviceName_____.listing
    - _____serviceName_____.details
    - _____serviceName_____.updated
