language: node_js

sudo: required
dist: trusty

env:
  - LD_RUN_PATH=/home/ubuntu/zeromq/lib LD_LIBRARY_PATH=/home/ubuntu/zeromq/lib PKG_CONFIG_PATH=/home/ubuntu/zeromq/lib/pkgconfig C_INCLUDE_PATH=/home/ubuntu/zeromq/include CPLUS_INCLUDE_PATH=/home/ubuntu/zeromq/include

node_js:
  - "4"
  - "5"
  - "6"


before_install:
  - npm install exosphere-shared
  - node_modules/exosphere-shared/bin/install-zeromq-ubuntu


before_script:
  - node_modules/o-tools-livescript/bin/build
  - git config --global user.email "circle@email.com"
  - git config --global user.name "circleci"


notifications:
  email: false
