name: Todo web server
description: serves the web UI of the Todo app

setup: npm install --loglevel error --depth 0
startup:
  command: node server.js
  online-text: Todo web server listening on port

messages:
  sends:
  receives:
