name: users
description: generic users service
author: exospheredev

setup: npm install --loglevel error --depth 0
startup:
  command: node_modules/exoservice/bin/exo-js
  online-text: online at port

messages:
  namespace: users
  receives:
    - users.list
    - users.create
  sends:
    - users.listed
    - users.created
