name: _____service-name_____
description: _____description_____

setup: npm install --loglevel error --depth 0
startup:
  command: node_modules/livescript/bin/lsc app
  online-text: all systems go

messages:
  sends:
  receives:
