title: test mongoDB service
description: generic mongoDB storage service
author: exospheredev

setup: npm install --loglevel error --depth 0
startup:
  command: node_modules/exoservice/bin/exo-js
  online-text: online at port

messages:
  receives:
    - mongo.list
    - mongo.create
  sends:
    - mongo.listed
    - mongo.created
