name: Example application
description: Demonstrates basic Exosphere application startup
version: '1.0'

dependencies:
  - type: exocom
    version: 0.22.0

services:
  public:
    crasher:
      location: ./crasher
    runner:
      location: ./runner
