name: _____serviceName_____
description: _____description_____

setup: npm install --loglevel error --depth 0
startup:
  command: node node_modules/exoservice/bin/exo-js
  online-text: all systems go

messages:
  receives:
    - ping
  sends:
    - pong
